-- ORDERS Table Definition

CREATE OR REPLACE TABLE ORDERS (
    ID INT GENERATED ALWAYS AS IDENTITY 
           (START WITH 1 INCREMENT BY 1),
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE DEFAULT CURRENT DATE NOT NULL,
    TOTAL_AMOUNT DECIMAL(11, 2) NOT NULL,
    STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL,
    
    PRIMARY KEY (ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) 
        REFERENCES CUSTOMER (ID) ON DELETE CASCADE
);

LABEL ON TABLE ORDERS IS 'Sales Orders Table';
